# Atelier ML - Partie 1 Préparation des données Pokémon

In [6]:
import numpy as nmp 
import pandas as pd 
pd.set_option('display.max_columns', None) # Afficher toutes les colonnes

## 1. Chargement du Pokédex

In [5]:
nosPokemons = pd.read_csv("datas/pokedex.csv")
print(nosPokemons.columns.values)

<StringArray>
[                 'NUMERO',                     'NOM',
                  'TYPE_1',                  'TYPE_2',
           'POINTS_DE_VIE',          'NIVEAU_ATTAQUE',
          'NIVEAU_DEFENSE', 'NIVEAU_ATTAQUE_SPECIALE',
 'NIVEAU_DEFENSE_SPECIALE',                 'VITESSE',
      'NOMBRE_GENERATIONS',              'LEGENDAIRE']
Length: 12, dtype: str

In [4]:
nosPokemons.head(10)

,NUMERO,NOM,TYPE_1,TYPE_2,POINTS_DE_VIE,NIVEAU_ATTAQUE,NIVEAU_DEFENSE,NIVEAU_ATTAQUE_SPECIALE,NIVEAU_DEFENSE_SPECIALE,VITESSE,NOMBRE_GENERATIONS,LEGENDAIRE
0,1,Bulbizarre,Herbe,Poison,45,49,49,65,65,45,1,FAUX
1,2,Herbizarre,Herbe,Poison,60,62,63,80,80,60,1,FAUX
2,3,Florizarre,Herbe,Poison,80,82,83,100,100,80,1,FAUX
3,4,Mega Florizarre,Herbe,Poison,80,100,123,122,120,80,1,FAUX
4,5,Salameche,Feu,NaN,39,52,43,60,50,65,1,FAUX
5,6,Reptincel,Feu,NaN,58,64,58,80,65,80,1,FAUX
6,7,Dracaufeu,Feu,Vol,78,84,78,109,85,100,1,FAUX
7,8,Mega Dracaufeu X,Feu,Dragon,78,130,111,130,85,100,1,FAUX
8,9,Mega Dracaufeu Y,Feu,Vol,78,104,78,159,115,100,1,FAUX
9,10,Carapuce,Eau,NaN,44,48,65,50,64,43,1,FAUX

## Transformation de LEGENDAIRE (VRAI/FAUX -> 1/0)

In [8]:
nosPokemonsClean = nosPokemons.copy()
nosPokemonsClean["LEGENDAIRE"] = nosPokemonsClean["LEGENDAIRE"].map({"VRAI": 1, "FAUX": 0}).astype(int)
nosPokemonsClean.head()

,NUMERO,NOM,TYPE_1,TYPE_2,POINTS_DE_VIE,NIVEAU_ATTAQUE,NIVEAU_DEFENSE,NIVEAU_ATTAQUE_SPECIALE,NIVEAU_DEFENSE_SPECIALE,VITESSE,NOMBRE_GENERATIONS,LEGENDAIRE
0,1,Bulbizarre,Herbe,Poison,45,49,49,65,65,45,1,0
1,2,Herbizarre,Herbe,Poison,60,62,63,80,80,60,1,0
2,3,Florizarre,Herbe,Poison,80,82,83,100,100,80,1,0
3,4,Mega Florizarre,Herbe,Poison,80,100,123,122,120,80,1,0
4,5,Salameche,Feu,NaN,39,52,43,60,50,65,1,0